services:
  coturn:
    image: coturn/coturn
    network_mode: bridge
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
      - "49160-49200:49160-49200/udp"
    command: >
      turnserver
      --lt-cred-mech
      --realm=example.com
      --user=user:pass
      --min-port=49160
      --max-port=49200
      --fingerprint
      --no-multicast-peers
      --no-cli
      --log-file=stdout

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - KRATOS_URL=http://kratos:4434
    depends_on:
      - kratos
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
      - ./public:/usr/share/nginx/html
    depends_on:
      - server

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - default

  kratos:
    image: oryd/kratos:v25.4.0
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      DSN: ${KRATOS_DSN}
    command: serve -c /etc/kratos/kratos.yaml
    volumes:
      - ./kratos/config:/etc/kratos
    networks:
      - default

  kratos-migrate:
    image: oryd/kratos:v25.4.0
    env_file:
      - .env
    command: migrate sql -e --yes
    environment:
      DSN: ${KRATOS_DSN}
    volumes:
      - ./kratos/config:/etc/kratos
    depends_on:
      - postgres

